import { Product } from '@/types/product';

export const products: Product[] = [
	{
		id: '1',
		slug: 'bpc-157',
		name: 'BPC 157',
		description: 'Tissue repair and recovery support for tendons, joints, and muscle health.',
		details: 'Often selected for soft-tissue support and post-training recovery routines, with a focus on mobility, comfort, and day-to-day resilience.',
		icons: ['Leaf', 'Flower2', 'Droplets'],
		price: 70.99,
		stock: 20,
		image: '/bottles/v01.png',
		category: 'Recovery',
	},
	{
		id: '2',
		slug: 'ghk-cu',
		name: 'GHK Cu',
		description: 'Skin rejuvenation peptide to support collagen, elasticity, and glow.',
		details: 'A copper peptide favored in dermal care protocols for tone and texture, supporting a smoother, brighter, and more refined appearance.',
		icons: ['Sparkles', 'Droplets', 'Leaf'],
		price: 70.99,
		stock: 20,
		image: '/bottles/v02.png',
		category: 'Skin',
	},
	{
		id: '3',
		slug: 'glutathione',
		name: 'Glutathione',
		description: 'Master antioxidant support for detox pathways and cellular defense.',
		details: 'Used to support oxidative balance and cellular resilience, helping the body maintain clarity, recovery, and overall detox support.',
		icons: ['Sparkles', 'Leaf', 'Droplets'],
		price: 70.99,
		stock: 20,
		image: '/bottles/v03.png',
		category: 'Antioxidant',
	},
	{
		id: '4',
		slug: 'ipamorelin',
		name: 'Ipamorelin',
		description: 'Gentle growth‑hormone support for recovery, sleep, and lean mass.',
		details: 'Commonly paired with nighttime recovery and restorative routines to support deeper rest, lean mass maintenance, and recovery cycles.',
		icons: ['Moon', 'Leaf', 'Sparkles'],
		price: 70.99,
		stock: 20,
		image: '/bottles/v04.png',
		category: 'Growth',
	},
	{
		id: '5',
		slug: 'mots-c',
		name: 'MOTS-C',
		description: 'Metabolic optimizer to support energy production and insulin balance.',
		details: 'Selected for metabolic efficiency and endurance support protocols, with an emphasis on steady energy output and glucose balance.',
		icons: ['Activity', 'Leaf', 'Droplets'],
		price: 70.99,
		stock: 20,
		image: '/bottles/v05.png',
		category: 'Metabolic',
	},
	{
		id: '6',
		slug: 'retratrutide',
		name: 'Retratrutide',
		description: 'Triple‑agonist metabolic support for weight and glucose balance.',
		details: 'Advanced metabolic signaling support for body composition programs, helping to guide appetite, energy use, and glucose management.',
		icons: ['Gauge', 'Leaf', 'Droplets'],
		price: 70.99,
		stock: 20,
		image: '/bottles/v06.png',
		category: 'Metabolic',
	},
	{
		id: '7',
		slug: 'tb-500',
		name: 'TB 500',
		description: 'Systemic recovery peptide to support mobility and soft‑tissue repair.',
		details: 'Often used in mobility-focused recovery stacks to support soft-tissue repair, flexibility, and smoother movement over time.',
		icons: ['HeartPulse', 'Leaf', 'Sparkles'],
		price: 70.99,
		stock: 20,
		image: '/bottles/v07.png',
		category: 'Recovery',
	},
	{
		id: '8',
		slug: 'tirzepatide',
		name: 'Tirzepatide',
		description: 'Dual‑agonist support for metabolic health and body composition.',
		details: 'Supports appetite signaling and metabolic balance goals, often selected for structured wellness and body composition routines.',
		icons: ['Scale', 'Leaf', 'Droplets'],
		price: 70.99,
		stock: 20,
		image: '/bottles/v08.png',
		category: 'Metabolic',
	},
	{
		id: '9',
		slug: 'tesamorelin',
		name: 'Tesamorelin',
		description: 'Longevity‑focused peptide to support fat metabolism and recovery.',
		details: 'Used in longevity routines for metabolic and recovery support, with an emphasis on healthy aging and ongoing vitality.',
		icons: ['Timer', 'Leaf', 'Sparkles'],
		price: 70.99,
		stock: 20,
		image: '/bottles/v09.png',
		category: 'Longevity',
	},
];
